FROM adoptopenjdk/openjdk14:slim AS builder

WORKDIR /nova-backend
COPY . /nova-backend

RUN apt-get update \
  && apt-get install git -y \
  && chmod +x ./gradlew \
  && ./gradlew installDist

FROM adoptopenjdk/openjdk14:jre

WORKDIR /data
COPY --from=builder /nova-backend/nova-bootstrap/build/install/nova-bootstrap/ /nova-backend/

ENTRYPOINT ["/nova-backend/bin/nova-bootstrap"]
